-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE users (
--     user_id SERIAL PRIMARY KEY,
--     username VARCHAR(50) NOT NULL,
--     email VARCHAR(100) UNIQUE,
--     password_hash VARCHAR(255) NOT NULL,
--     registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
