version: '3.6'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Muraai@123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=muraai
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    restart: always
#    volumes:
#    - db_data:/var/lib/postgresql/data
  graphql-engine:
    #image: hasura/graphql-engine:v1.0.0-beta.6
    image: hasura/graphql-engine:v2.18.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Muraai%40123@postgres:5432/muraai
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
#volumes:
#  db_data:
