version: '3.7'

services:
  hasura:
    image: hasura/graphql-engine:v2.18.0
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Muraai%40123@db:5432/muraai
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: muraai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Muraai@123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
